version: '3'

services:

  frontend:
    container_name: mesto-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    restart: always

  backend:
    container_name: mesto-backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports: 
      - '3001:3001'
    restart: always

  mongo:
    container_name: mesto-mongo
    image: mongo
    restart: always

  mongo-express:
    container_name: mesto-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/